const stocks = [
  {
    name:"ASX:INR",
    symbolsCode:"INR.AU",
    category:"Stock",
    latestPrice:"2885.84",
    updateDate:"10/07/2023",
    difference:"0"
  },
  {
    name:"ASX:ARU",
    symbolsCode:"ARU.AU",
    category:"Stock",
    latestPrice:"2885.84",
    updateDate:"10/07/2023",
    difference:"0"
  },
  {
    name:"ASX:DVP",
    symbolsCode:"DVP.AU",
    category:"Stock",
    latestPrice:"2885.84",
    updateDate:"10/07/2023",
    difference:"0"
  },
  {
    name:"ASX:GRR",
    symbolsCode:"GRR.AU",
    category:"Stock",
    latestPrice:"2885.84",
    updateDate:"10/07/2023",
    difference:"0"
  },
  {
    name:"ASX:AZS",
    symbolsCode:"AZS.AU",
    category:"Stock",
    latestPrice:"2885.84",
    updateDate:"10/07/2023",
    difference:"0"
  },
  {
    name:"ASX:SYR",
    symbolsCode:"SYR.AU",
    category:"Stock",
    latestPrice:"2885.84",
    updateDate:"10/07/2023",
    difference:"0"
  },
  {
    name:"ASX:PMT",
    symbolsCode:"PMT.AU",
    category:"Stock",
    latestPrice:"2885.84",
    updateDate:"10/07/2023",
    difference:"0"
  },
  {
    name:"ASX:TIE",
    symbolsCode:"TIE.AU",
    category:"Stock",
    latestPrice:"2885.84",
    updateDate:"10/07/2023",
    difference:"0"
  },
  {
    name:"ASX:AGY",
    symbolsCode:"AGY.AU",
    category:"Stock",
    latestPrice:"2885.84",
    updateDate:"10/07/2023",
    difference:"0"
  },
  {
    name:"ASX:TLG",
    symbolsCode:"TLG.AU",
    category:"Stock",
    latestPrice:"2885.84",
    updateDate:"10/07/2023",
    difference:"0"
  },
  
];

module.exports = stocks;
